#ifndef _KEYMAP_H_
#define _KEYMAP_H_

#include "pico/stdlib.h"
#include "config.h"
#include "usb_descriptors.h"
#include <tusb.h>
//--------------------------------------------------------------------+
// USB HID /*int a  = 0; */
//--------------------------------------------------------------------+
// HID_KEY_F21 is top left numpad macro.



uint8_t key_map_standard[TOTAL_BITS] = {
    //40 Bits, 40 keys left side. 
    HID_KEY_SPACE/*Left spaceU*/, HID_KEY_BACKSPACE/*CENTER SPACEF*/, HID_KEY_SPACE, HID_KEY_F17/*MACRO5*/, HID_KEY_F13/*MACRO1*/, HID_KEY_F14/*Macro2*/, HID_KEY_F15/*MACRO3*/, HID_KEY_F16/*MACRO4*/,
    HID_KEY_SHIFT_LEFT, HID_KEY_CAPS_LOCK, HID_KEY_TAB, HID_KEY_F2, HID_KEY_F1, HID_KEY_ESCAPE, HID_KEY_1, HID_KEY_GRAVE,
    HID_KEY_S, HID_KEY_A, HID_KEY_Z, HID_KEY_ALT_LEFT, HID_KEY_GUI_LEFT, HID_KEY_Q, HID_KEY_2, HID_KEY_CONTROL_LEFT,
    HID_KEY_4, HID_KEY_R, HID_KEY_E, HID_KEY_F4, HID_KEY_F3, HID_KEY_W, HID_KEY_3, HID_KEY_X,
    HID_KEY_5, HID_KEY_T, HID_KEY_G, HID_KEY_B, HID_KEY_V, HID_KEY_C, HID_KEY_F, HID_KEY_D,
    
        //56 keys on right side, 50 keys used.
   HID_KEY_PAGE_UP, HID_KEY_F20 /*UNPLUGGED*/, HID_KEY_F20 /*UNPLUGGED*/, HID_KEY_INSERT, HID_KEY_F20 /*UNPLUGGED*/,HID_KEY_F20 /*UNPLUGGED*/,HID_KEY_F20 /*UNPLUGGED*/,HID_KEY_F20 /*UNPLUGGED*/,
  HID_KEY_PAGE_DOWN, HID_KEY_HOME, HID_KEY_F20 /*UNPLUGGED*/, HID_KEY_DELETE, HID_KEY_F12, HID_KEY_ARROW_RIGHT, HID_KEY_BACKSPACE, HID_KEY_ARROW_DOWN,
   HID_KEY_ARROW_LEFT, HID_KEY_ARROW_UP, HID_KEY_BACKSLASH, HID_KEY_ENTER, HID_KEY_F11, HID_KEY_SHIFT_RIGHT, HID_KEY_CONTROL_RIGHT, HID_KEY_GUI_RIGHT, 
   HID_KEY_EQUAL, HID_KEY_BRACKET_RIGHT /*close bracket*/, HID_KEY_SLASH, HID_KEY_APOSTROPHE, HID_KEY_F9, HID_KEY_MINUS, HID_KEY_BRACKET_LEFT/*open bracket*/,  HID_KEY_ALT_RIGHT,
   HID_KEY_0, HID_KEY_SEMICOLON, HID_KEY_COMMA, HID_KEY_PERIOD, HID_KEY_F10, HID_KEY_P, HID_KEY_L, HID_KEY_O,
   HID_KEY_M, HID_KEY_9, HID_KEY_K, HID_KEY_I, HID_KEY_F8, HID_KEY_J, HID_KEY_8, HID_KEY_N,
   HID_KEY_7, HID_KEY_U, HID_KEY_H, HID_KEY_F7, HID_KEY_F6, HID_KEY_F5, HID_KEY_Y, HID_KEY_6,

    //24 bits for numpad, 21 keys or 18 keys 
  HID_KEY_KEYPAD_SUBTRACT, HID_KEY_KEYPAD_ADD, HID_KEY_F20 /*UNPLUGGED*/,  HID_KEY_F24 /*VOLUMEKNOB*/, HID_KEY_KEYPAD_ENTER, HID_KEY_KEYPAD_3,
  HID_KEY_KEYPAD_6, HID_KEY_KEYPAD_9, HID_KEY_KEYPAD_DIVIDE, HID_KEY_KEYPAD_DECIMAL, HID_KEY_KEYPAD_MULTIPLY, HID_KEY_F23 /*Top right half key*/, HID_KEY_F20 /*UNPLUGGED*/,
   HID_KEY_KEYPAD_2, HID_KEY_KEYPAD_5, HID_KEY_KEYPAD_8, HID_KEY_F20 /*UNPLUGGED*/, HID_KEY_KEYPAD_0, HID_KEY_KEYPAD_1, HID_KEY_F22 /*Top middle half key*/, HID_KEY_F21 /*Top left half key*/,
   HID_KEY_KEYPAD_4, HID_KEY_KEYPAD_7, HID_KEY_NUM_LOCK
};

uint8_t key_map_noright[TOTAL_BITS] = {
    HID_KEY_5, HID_KEY_T, HID_KEY_G, HID_KEY_B, HID_KEY_V, HID_KEY_C, HID_KEY_F, HID_KEY_D,
    HID_KEY_4, HID_KEY_R, HID_KEY_E, HID_KEY_F4, HID_KEY_F3, HID_KEY_W, HID_KEY_3, HID_KEY_X,
    HID_KEY_S, HID_KEY_A, HID_KEY_Z, HID_KEY_Q, HID_KEY_ALT_LEFT, HID_KEY_CONTROL_LEFT, HID_KEY_2, HID_KEY_GUI_LEFT,
    HID_KEY_SHIFT_LEFT, HID_KEY_CAPS_LOCK, HID_KEY_TAB, HID_KEY_F2, HID_KEY_F1, HID_KEY_ESCAPE, HID_KEY_1, HID_KEY_GRAVE,
    HID_KEY_F20 /*UNPLUGGED*/, HID_KEY_F20 /*UNPLUGGED*/, HID_KEY_F20 /*UNPLUGGED*/, 
    HID_KEY_F17, HID_KEY_F20, HID_KEY_F14, HID_KEY_F16, HID_KEY_F15,

    HID_KEY_KEYPAD_SUBTRACT, HID_KEY_KEYPAD_ADD, HID_KEY_F20 /*UNPLUGGED*/,  HID_KEY_F24 /*VOLUMEKNOB*/, HID_KEY_KEYPAD_ENTER, HID_KEY_KEYPAD_3,
    HID_KEY_KEYPAD_6, HID_KEY_KEYPAD_9, HID_KEY_KEYPAD_DIVIDE, HID_KEY_KEYPAD_DECIMAL, HID_KEY_KEYPAD_MULTIPLY, HID_KEY_F23 /*Top right half key*/, HID_KEY_F20 /*UNPLUGGED*/,
    HID_KEY_KEYPAD_2, HID_KEY_KEYPAD_5, HID_KEY_KEYPAD_8, HID_KEY_F20 /*UNPLUGGED*/, HID_KEY_KEYPAD_0, HID_KEY_KEYPAD_1, HID_KEY_F22 /*Top middle half key*/, HID_KEY_F21 /*Top left half key*/,
    HID_KEY_KEYPAD_4, HID_KEY_KEYPAD_7, HID_KEY_NUM_LOCK,

    HID_KEY_F20 /*UNPLUGGED*/,HID_KEY_F20 /*UNPLUGGED*/,HID_KEY_F20 /*UNPLUGGED*/,HID_KEY_F20 /*UNPLUGGED*/,HID_KEY_F20 /*UNPLUGGED*/,HID_KEY_F20 /*UNPLUGGED*/,HID_KEY_F20 /*UNPLUGGED*/,HID_KEY_F20 /*UNPLUGGED*/,
    HID_KEY_F20 /*UNPLUGGED*/,HID_KEY_F20 /*UNPLUGGED*/,HID_KEY_F20 /*UNPLUGGED*/,HID_KEY_F20 /*UNPLUGGED*/,HID_KEY_F20 /*UNPLUGGED*/,HID_KEY_F20 /*UNPLUGGED*/,HID_KEY_F20 /*UNPLUGGED*/,HID_KEY_F20 /*UNPLUGGED*/,
    HID_KEY_F20 /*UNPLUGGED*/,HID_KEY_F20 /*UNPLUGGED*/,HID_KEY_F20 /*UNPLUGGED*/,HID_KEY_F20 /*UNPLUGGED*/,HID_KEY_F20 /*UNPLUGGED*/,HID_KEY_F20 /*UNPLUGGED*/,HID_KEY_F20 /*UNPLUGGED*/,HID_KEY_F20 /*UNPLUGGED*/,
    HID_KEY_F20 /*UNPLUGGED*/,HID_KEY_F20 /*UNPLUGGED*/,HID_KEY_F20 /*UNPLUGGED*/,HID_KEY_F20 /*UNPLUGGED*/,HID_KEY_F20 /*UNPLUGGED*/,HID_KEY_F20 /*UNPLUGGED*/,HID_KEY_F20 /*UNPLUGGED*/,HID_KEY_F20 /*UNPLUGGED*/,
    HID_KEY_F20 /*UNPLUGGED*/,HID_KEY_F20 /*UNPLUGGED*/,HID_KEY_F20 /*UNPLUGGED*/,HID_KEY_F20 /*UNPLUGGED*/,HID_KEY_F20 /*UNPLUGGED*/,HID_KEY_F20 /*UNPLUGGED*/,HID_KEY_F20 /*UNPLUGGED*/,HID_KEY_F20 /*UNPLUGGED*/,
    HID_KEY_F20 /*UNPLUGGED*/,HID_KEY_F20 /*UNPLUGGED*/,HID_KEY_F20 /*UNPLUGGED*/,HID_KEY_F20 /*UNPLUGGED*/,HID_KEY_F20 /*UNPLUGGED*/,HID_KEY_F20 /*UNPLUGGED*/,HID_KEY_F20 /*UNPLUGGED*/,HID_KEY_F20 /*UNPLUGGED*/,
    HID_KEY_F20 /*UNPLUGGED*/,HID_KEY_F20 /*UNPLUGGED*/,HID_KEY_F20 /*UNPLUGGED*/,HID_KEY_F20 /*UNPLUGGED*/,HID_KEY_F20 /*UNPLUGGED*/,HID_KEY_F20 /*UNPLUGGED*/,HID_KEY_F20 /*UNPLUGGED*/,HID_KEY_F20 /*UNPLUGGED*/


};


   

#endif
